# Generated by Django 4.2.6 on 2023-10-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_comment_webcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='description',
            field=models.TextField(),
        ),
    ]
